export const AUTH_SERVICE_OPTIONS = 'AUTH_SERVICE_OPTIONS';
export const TSS_AUTH_API = 'TSS_AUTH_API';
export const AXIOS_INTERCEPTOR = 'AXIOS_INTERCEPTOR';
export const AXIOS_PROVIDER = 'AXIOS_PROVIDER';
export const PUBLIC_ACCESS = 'PUBLIC';
export const ACCESS_CLAIMS_EXTRACTOR = 'ACCESS_CLAIMS_EXTRACTOR';