export const AUTH_SERVICE_OPTIONS = 'AUTH_SERVICE_OPTIONS';
export const AXIOS_INTERCEPTOR = 'AXIOS_INTERCEPTOR';
export const AXIOS_PROVIDER = 'AXIOS_PROVIDER';
export const ANONYMOUS_USER = 'ANONYMOUS_USER';
export const ACCESS_CLAIMS_EXTRACTOR = 'ACCESS_CLAIMS_EXTRACTOR';
export const CACHE_KEY_RESOLVER = "CACHE_KEY_RESOLVER"
export const AUTH_API_KEY_RESOLVER = 'AUTH_API_KEY_PROVIDER'
